name: Run Web Crawler

on:
  schedule:
    - cron: '*/40 * * * *' 
  workflow_dispatch: 

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install --with-deps chromium

      - name: Verify Playwright installation
        run: |
          playwright --version
          ls -la /home/runner/.cache/ms-playwright/  # Verifica se os binários foram baixados

      - name: Run crawler
        run: |
          python execucao.py
