name: Run Web Crawler Marketplace

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    environment: production  # Substitua por nome do seu ambiente
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install --with-deps chromium

      - name: Verify Playwright installation
        run: |
          playwright --version
          ls -la /home/runner/.cache/ms-playwright/

      - name: Run crawler
        env:
          API_ENDPOINT: ${{ env.ENDPOINT }}  # Mapeia ENDPOINT do ambiente para API_ENDPOINT
        run: |
          python execucao.py
